config/routes.rb
Rails.application.routes.draw do
  resources :careers, only: [:index, :show, :new, :create, :destroy] do
    resources :job_applications, only: [:new, :create]
  end

  resources :job_applications, only: [:index, :show, :destroy]
end

app/models/career.rb
class Career < ActiveRecord::Base
  has_many :job_applications

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  belongs_to :career
  has_many :previous_jobs
  accepts_nested_attributes_for :previous_jobs

  validates :full_name, presence: true
  validates :email, presence: true
end

app/models/previous_job.rb
class PreviousJob < ActiveRecord::Base
  belongs_to :job_application

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
    @careers = Career.all.order(:title)
  end

  def show
    @career = Career.find(params[:id])
  end

  def new
    @career = Career.new
  end

  def create
    @career = Career.new(career_params)
    if @career.save
      redirect_to careers_path, notice: 'Career created!'
    else
      render :new
    end 
  end

  def destroy
    Career.destroy(params[:id])
    redirect_to careers_path
  end

  private

  def career_params
    params.require(:career).permit(:title, :location, :description)
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def index
    @job_applications = JobApplication.all.group(:career_id)
  end

  def show
    @job_application = JobApplication.find(params[:id])
  end

  def new
    @job_application = career.job_applications.new
    3.times { @job_application.previous_jobs.new }
  end

  def create
    @job_application = career.job_applications.new(job_application_params)
    if @job_application.save 
      redirect_to careers_path
    else
      render :new
    end
  end

  def destroy
    JobApplication.destroy(params[:id])
    redirect_to job_applications_path
  end

  private

  def career
    Career.find(params[:career_id])
  end

  def job_application_params
    params.require(:job_application).
           permit(:full_name,
                  :email,
                  previous_jobs_attributes: [:title,
                                             :start_on,
                                             :leave_on,
                                             :leave_reason])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/careers/_career.html.erb
<li>
  <%= link_to career.title, career_path(career) %> in <%= career.location %>
</li>

app/views/careers/index.html.erb
<h1>Careers</h1>

<ul><%= render @careers %></ul>

<h2>Admin</h2>

<ul>
  <li><%= link_to 'Add New Career', new_career_path %></li>
  <li><%= link_to 'View All Applications', job_applications_path %></li>
</ul>

app/views/careers/new.html.erb
<h1>New Career</h1>

<% if @career.errors.any? %>
  <ul>
    <% @career.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @career do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'Create This Career' %>
<% end %>

app/views/careers/show.html.erb
<h1><%= @career.title %></h1>
<h2>Located in <%= @career.location %></h2>

<p><%= @career.description %></p>

<%= link_to 'Apply Online Now!', new_career_job_application_path(@career) %>

<br/>

<%= link_to 'Delete this Career', career_path(@career), method: :delete %>

app/views/job_applications/_job_application.html.erb
<li>
<strong><%= job_application.career.title %></strong> <%= link_to job_application.full_name, job_application_path(job_application) %> (<%= job_application.email %>) | <%= link_to 'Delete', job_application_path(job_application), method: :delete %>
</li>

app/views/job_applications/index.html.erb
<h1>Job Applications</h1>

<ul><%= render @job_applications %></ul>

<%= link_to 'Back', careers_path %>

app/views/job_applications/new.html.erb
<h1><%= @job_application.career.title %> Application</h1>

<% if @job_application.errors.any? %>
  <ul>
    <% @job_application.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@job_application.career, @job_application] do |f| %>
  <%= f.label :full_name %>
  <%= f.text_field :full_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <h3>Previous Employment</h3>

  <%= f.fields_for :previous_jobs do |ff| %>
    <h4>Position <%= ff.index + 1 %></h4>

    <% @job_application.previous_jobs[ff.index].errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
    <% end %>

    <%= ff.label :title %>
    <%= ff.text_field :title %>

    <%= ff.label :start_on %>
    <%= ff.date_field :start_on %>

    <%= ff.label :leave_on %>
    <%= ff.date_field :leave_on %>

    <%= ff.label :leave_reason %>
    <%= ff.text_field :leave_reason %>
  <% end %>

  <%= f.submit 'Apply!' %>
<% end %>

app/views/job_applications/show.html.erb
<h1><%= @job_application.career.title %> Application</h1>

<h2>Applicant Information</h2>

<div id="applicant-bio">
  <span><%= @job_application.full_name %></span>
  <span><%= @job_application.email %></span>
</div>

<h3>Previous Work History</h3>

<%= link_to 'Back', job_applications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nested</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'flashes' %>
  <%= yield %>
</body>
</html>